/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:side:390073:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:side:390073:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  side = new GSlider(this, 19, 17, 277, 100, 10.0);
  side.setShowValue(true);
  side.setShowLimits(true);
  side.setLimits(1, 0, 30);
  side.setShowTicks(true);
  side.setNumberFormat(G4P.INTEGER, 0);
  side.setOpaque(false);
  side.addEventHandler(this, "slider1_change1");
}

// Variable declarations 
// autogenerated do not edit
GSlider side; 
